import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ST6 Material Design 3 Dark Theme
        "on-error": "#690005",
        "outline-variant": "#514532",
        "surface-bright": "#3a3939",
        "tertiary-container": "#00d2fe",
        surface: "#131313",
        "on-surface-variant": "#d6c4ac",
        tertiary: "#a4e7ff",
        secondary: "#eac07d",
        "on-primary-container": "#6b4900",
        "primary-fixed": "#ffdeac",
        "primary-fixed-dim": "#ffba38",
        "secondary-fixed-dim": "#eac07d",
        "tertiary-fixed-dim": "#43d6ff",
        "on-primary-fixed-variant": "#604100",
        error: "#ffb4ab",
        "inverse-primary": "#7e5700",
        "on-primary-fixed": "#281900",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#432c00",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353534",
        "inverse-on-surface": "#313030",
        "primary-container": "#ffb300",
        outline: "#9e8e78",
        "surface-dim": "#131313",
        "on-secondary-fixed": "#281900",
        "on-background": "#e5e2e1",
        "surface-tint": "#ffba38",
        "surface-variant": "#353534",
        "on-primary": "#432c00",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5e4109",
        "on-tertiary": "#003543",
        background: "#131313",
        "secondary-fixed": "#ffdeac",
        primary: "#ffd79b",
        "on-secondary-container": "#dbb270",
        "secondary-container": "#61440c",
        "on-tertiary-container": "#00566a",
        "on-tertiary-fixed": "#001f28",
        "tertiary-fixed": "#b5ebff",
        "on-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004e60",
        "surface-container": "#201f1f",
        terminal: "#00ff41",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      animation: {
        blink: "blink 1s step-end infinite",
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
